name: "skipped matrix"

on:
  workflow_dispatch:
    
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    
    if: ${{ github.triggering_actor != 'allanguigou' }} # don't run if i initiated the PR
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]
    steps:
      - name: hello
        run: echo hello
